# Generated by Django 3.2.6 on 2021-08-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20210818_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prakasham',
            new_name='Prakasam',
        ),
    ]
