# Generated by Django 3.2.6 on 2021-09-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20210819_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(default='', max_length=254)),
                ('message', models.TextField(default='', max_length=5000)),
            ],
        ),
    ]
