# Generated by Django 3.2.6 on 2021-09-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus',
            new_name='contact',
        ),
    ]
